/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inheritanceproject;


import inheritanceproject.heirs.Heirs;
import inheritanceproject.heirs.Heir;
import inheritanceproject.heirs.HeirsFilter;
import javax.swing.JComboBox;

/**
 *
 * @author yassine
 */
public class InheritanceGUI extends javax.swing.JPanel {

    /**
     * Creates new form InheritanceGUI
     */
    public InheritanceGUI() {
        initComponents();
        heirs = new Heirs();
        filter= new HeirsFilter(heirs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fatherComboBox = new javax.swing.JComboBox();
        motherComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        husbandComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        wifeComboBox = new javax.swing.JComboBox();
        solveButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sonField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        daughterField = new javax.swing.JTextField();

        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Amount");

        jLabel2.setText("Father");

        fatherComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "yes", "no" }));
        fatherComboBox.setSelectedIndex(1);

        motherComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "yes", "no" }));
        motherComboBox.setSelectedIndex(1);

        jLabel3.setText("Mother");

        jLabel4.setText("Husband");

        husbandComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "yes", "no" }));
        husbandComboBox.setSelectedIndex(1);
        husbandComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                husbandComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Wife");

        wifeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "yes", "no" }));
        wifeComboBox.setSelectedIndex(1);
        wifeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wifeComboBoxActionPerformed(evt);
            }
        });

        solveButton.setText("Solve");
        solveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Son");

        jLabel7.setText("Daugther");

        daughterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daughterFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(daughterField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(solveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sonField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(43, 43, 43))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(motherComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fatherComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(husbandComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wifeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(amountField)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fatherComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(sonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motherComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(daughterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(husbandComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(wifeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(solveButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldActionPerformed

    private void husbandComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_husbandComboBoxActionPerformed

        if(evt.getSource() instanceof JComboBox){
            switch(((JComboBox)evt.getSource()).getSelectedItem().toString()) {
                case "yes":
                    this.wifeComboBox.setSelectedIndex(1);
                
            }
        }
        
        this.updateUI();
    }//GEN-LAST:event_husbandComboBoxActionPerformed

    private void wifeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wifeComboBoxActionPerformed
        if(evt.getSource() instanceof JComboBox){
            switch(((JComboBox)evt.getSource()).getSelectedItem().toString()) {
                case "yes":
                    this.husbandComboBox.setSelectedIndex(1);
                
            }
        }
    }//GEN-LAST:event_wifeComboBoxActionPerformed

    private void solveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveButtonActionPerformed
        heirs.clear();
        heirs.resetRemainingQuota();
        if(this.fatherComboBox.getModel().getSelectedItem().equals("yes")) {
            heirs.addHeir("father", 1);
        }
        if(this.motherComboBox.getModel().getSelectedItem().equals("yes")) {
            heirs.addHeir("mother", 1);
        }
        if(this.husbandComboBox.getModel().getSelectedItem().equals("yes")) {
           heirs.addHeir("husband", 1);
        }
        if(this.wifeComboBox.getModel().getSelectedItem().equals("yes")) {
            heirs.addHeir("wife", 1);
        }
        if(!this.daughterField.getText().isEmpty()) {
            int daugthers = Integer.valueOf(this.daughterField.getText());
            
            if(daugthers > 0) {
                heirs.addHeir("daugther", daugthers);
            }
        }
        if(!this.sonField.getText().isEmpty()) {
            int sons = Integer.valueOf(this.sonField.getText());
            if(sons > 0) {
                heirs.addHeir("son", sons);
            }
        }
        
        filter.start();
        
        for(int i = 0 ;i<heirs.getSize(); i++)
            System.out.println(heirs.getHeir(i).getDegree() + " " + heirs.getHeir(i).getQuota());
        
        System.out.println("Remaining quota : " + Heir.m_remaining_quota);
    }//GEN-LAST:event_solveButtonActionPerformed

    private void daughterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daughterFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daughterFieldActionPerformed

Heirs heirs;
HeirsFilter filter;
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JTextField daughterField;
    private javax.swing.JComboBox fatherComboBox;
    private javax.swing.JComboBox husbandComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox motherComboBox;
    private javax.swing.JButton solveButton;
    private javax.swing.JTextField sonField;
    private javax.swing.JComboBox wifeComboBox;
    // End of variables declaration//GEN-END:variables
}
